FROM linuxserver/plex:latest

LABEL maintainer="pabloromeo"

COPY /docker-mod/root/etc/ /etc/
COPY /app /app

RUN apt-get update && \
    apt-get install -y dos2unix && \
    dos2unix /etc/s6-overlay/s6-rc.d/1-install-dependencies/run && \
    dos2unix /etc/s6-overlay/s6-rc.d/2-npm-install/run && \
    dos2unix /etc/s6-overlay/s6-rc.d/3-install-transcoder-shim/run && \
    dos2unix /etc/s6-overlay/s6-rc.d/4-setup-relay/run && \
    dos2unix /etc/s6-overlay/s6-rc.d/5-run-relay/run && \
    dos2unix /app/transcoder-shim.sh && \
    dos2unix /app/sentinel.sh && \
    apt-get remove -y dos2unix

RUN bash /etc/s6-overlay/s6-rc.d/1-install-dependencies/run && \
    bash /etc/s6-overlay/s6-rc.d/2-npm-install/run && \
    rm -rf /etc/s6-overlay/s6-rc.d/1-install-dependencies && \
    rm -rf /etc/s6-overlay/s6-rc.d/2-npm-install && \
    rm -rf /etc/s6-overlay/s6-rc.d/3-install-transcoder-shim/dependencies.d && \
    rm -rf /etc/s6-overlay/s6-rc.d/4-setup-relay/dependencies.d && \
    rm /etc/s6-overlay/s6-rc.d/user/contents.d/1-install-dependencies && \
    rm /etc/s6-overlay/s6-rc.d/user/contents.d/2-npm-install && \
    echo "**** cleanup ****" && \
    rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

WORKDIR /
