#!/usr/bin/with-contenv bash

echo "**** configuring HAProxy (for Local Relay) ****"
echo "PMS_PORT => '${PMS_PORT}'"
echo "LOCAL_RELAY_PORT => '${LOCAL_RELAY_PORT}'"

sed -i 's/_PMS_PORT/'"${PMS_PORT:-32400}"'/g' /etc/haproxy/haproxy.cfg
sed -i 's/_LOCAL_RELAY_PORT/'"${LOCAL_RELAY_PORT:-32499}"'/g' /etc/haproxy/haproxy.cfg

if [[ ! -s /proc/net/if_inet6 ]]; then
    sed -i '/^[[:space:]]*bind \[::\]:/d' /etc/haproxy/haproxy.cfg
fi

/usr/sbin/haproxy -c -f /etc/haproxy/haproxy.cfg || exit 1
echo "**** HAProxy configuration complete ****"
