#!/usr/bin/with-contenv bash

set -e
export DEBIAN_FRONTEND=noninteractive

if ! command -v node >/dev/null 2>&1 || ! command -v haproxy >/dev/null 2>&1; then
    apt-get update
    apt-get -y -o Dpkg::Options::=--force-confold -o Dpkg::Use-Pty=0 \
        install libatomic1 file haproxy

    if ! command -v node >/dev/null 2>&1; then
        curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
        bash n lts
    fi
fi
