#!/usr/bin/with-contenv bash

if which node > /dev/null && which haproxy > /dev/null
then
    echo "**** node and haproxy are installed, skipping... ****"
else
    echo "**** install runtime packages ****"
    echo "**** apt-get update ****"
    apt-get update
    echo "**** install libatomic1, file, haproxy ****"
    apt-get install -y libatomic1 file haproxy

    if which node > /dev/null
    then
        echo "**** node is installed, skipping... ****"
    else
        echo "**** install 'n' ****"
        curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
        echo "**** install nodejs ****"
        bash n lts
    fi
fi
